/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        bg: "var(--bg)",
        "bg-deep": "var(--bg-deep)",
        "bg-subtle": "var(--bg-subtle)",
        "bg-raise": "var(--bg-raise)",
        "bg-hover": "var(--bg-hover)",
        "bg-overlay": "var(--bg-overlay)",
        ink: "var(--ink)",
        "ink-2": "var(--ink-2)",
        "ink-3": "var(--ink-3)",
        line: "var(--line)",
        "line-soft": "var(--line-soft)",
        accent: "var(--accent)",
        "accent-d": "var(--accent-d)",
        "accent-soft": "var(--accent-soft)",
        "accent-ink": "var(--accent-ink)",
        success: "var(--success)",
        "success-bg": "var(--success-bg)",
        "success-border": "var(--success-border)",
        "success-text": "var(--success-text)",
        warning: "var(--warning)",
        "warning-bg": "var(--warning-bg)",
        "warning-border": "var(--warning-border)",
        "warning-text": "var(--warning-text)",
        danger: "var(--danger)",
        "danger-bg": "var(--danger-bg)",
        "danger-border": "var(--danger-border)",
        "danger-text": "var(--danger-text)",
        info: "var(--info)",
        "info-bg": "var(--info-bg)",
        "info-border": "var(--info-border)",
        "info-text": "var(--info-text)",
      },
      fontFamily: {
        sans: ["var(--font)"],
        mono: ["var(--font-mono)"],
      },
      borderRadius: {
        sm: "var(--radius)",
        DEFAULT: "var(--radius)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
      },
      boxShadow: {
        sm: "var(--shadow-sm)",
        md: "var(--shadow-md)",
        card: "var(--shadow-card)",
        glow: "var(--shadow-glow)",
        pop: "var(--shadow-pop)",
      },
    },
  },
  plugins: [],
};
